version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt-get update -y
      - apt-get install -y yarn
  pre_build:
    commands:
      - echo Installing NPM dependencies
      - yarn install
  build:
    commands:
      - echo build started on `date`
      - zip -r timeTracking.zip src lambda.js node_modules
      - aws lambda update-function-code --function-name $Stage-cf-eds37-timetracking-app --zip-file "fileb://timeTracking.zip"

